const { chromium } = require('playwright');
(async()=>{
 const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1100,height:900}});
 const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await p.goto('file://'+process.cwd()+'/preview.html'); await p.waitForTimeout(500);
 await p.screenshot({path:'s_home.png', fullPage:true});
 await p.click('[data-go="l2"] >> nth=0'); await p.waitForTimeout(500);
 await p.fill('#l2-b0','광개토대왕'); await p.fill('#l2-b1','무령왕'); await p.click('[data-check="l2"]'); await p.waitForTimeout(300);
 await p.screenshot({path:'s_l2.png', fullPage:true});
 await p.click('.nav [data-go="play"]'); await p.waitForTimeout(300);
 await p.click('[data-det] >> nth=0'); await p.waitForTimeout(200);
 await p.screenshot({path:'s_play.png', fullPage:true});
 await p.setViewportSize({width:390,height:844});
 await p.click('.nav [data-go="final"]'); await p.waitForTimeout(300);
 for(let i=0;i<10;i++) await p.check(`input[name=fq${i}] >> nth=1`);
 await p.click('[data-finalsubmit]'); await p.waitForTimeout(600);
 await p.screenshot({path:'s_final_m.png', fullPage:true});
 console.log('ERR', JSON.stringify(errs));
 await b.close();
})();
